### ISSUE TITLE
X1-AV-15 HX711 Testing reading

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-flight-Computer#27]
**Description**
- Talk to JJ and figure how we are going to read the data from his PCB to the flight computer.

**Acceptance Criteria**
- Software is written that knows how to receive and handle 12 different strain gauge values from 1 hdmi input 
- Plan for how to wire HDMI cable to rpi is added to KiCAD schematic that @apthornwell is making in #25 

**Dev Notes**

[Write notes on why you choose the wiring that you did. Explain how software works. Document in Pull request description]

**Comment by cjsquires** [comment]
This library works for the HX711 (and is in python) https://github.com/gandalf15/HX711/
It the python file of the driver is rather large, but should work. The file also has all the validity checks included, and is very well documented. 

If it turns out to be too much for the flight computer to handle, then we could also call the compiled c driver from python.

I can clarify anything that’s confusing to anyone (hopefully)

**Comment by jjderooy** [comment]
I had a look at the python lib you linked. It looks pretty good but will need to be modified since we are  using multiple HX711s with a single clock line. Basically the way it works is the flight computer will pulse the clock line, and the HX711 will send data back on the data line. The lib you linked only allows one HX711 (ie one data line) per clock line.

Up to you whether you think it will be easier to modify the library or write your own. After reading through the code, there is a lot of extra error checking and functions which don't really apply to what we're doing like setting the output to kilograms and that sort of thing. Most of these libraries are designed to use HX711s for kitchen weigh scales which is why they have all those features.

Up to you whether you think it will be easier to modify the library or write your own. Alternatively, here is a [multi HX711 Arduino](https://github.com/shmulike/HX711-multi) library that you could convert to python.

**Comment by TechGal** [comment]
Move to next sprint. 
- converting c++ to python

**Comment by jjderooy** [comment]
Finished in #56.
